import type { App } from "vue";
import { VueQueryPlugin } from "@tanstack/vue-query";
import Vue3Toastify, { toast, type ToastContainerOptions } from "vue3-toastify";
import PrimeVue from "primevue/config";
export default (app: App) => {
  app.use(VueQueryPlugin);
  app.use(Vue3Toastify, {
    autoClose: 800,
    position: toast.POSITION.TOP_RIGHT,
  } as ToastContainerOptions);
  app.use(PrimeVue, {
    locale: {
      startsWith: "Empieza con",
      contains: "Contiene",
      notContains: "No contiene",
      endsWith: "Termina con",
      equals: "Igual a",
      notEquals: "Diferente de",
      noFilter: "Sin filtro",
      lt: "Menor que",
      lte: "Menor o igual a",
      gt: "Mayor que",
      gte: "Mayor o igual a",
      dateIs: "La fecha es",
      dateIsNot: "La fecha no es",
      dateBefore: "La fecha es antes de",
      dateAfter: "La fecha es después de",
      clear: "Limpiar",
      apply: "Aplicar",
      matchAll: "Coincide con todos",
      matchAny: "Coincide con alguno",
      addRule: "Agregar regla",
      removeRule: "Eliminar regla",
      accept: "Sí",
      reject: "No",
      choose: "Elegir",
      upload: "Subir",
      cancel: "Cancelar",
      completed: "Completado",
      pending: "Pendiente",
      fileSizeTypes: ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
      dayNames: [
        "Domingo",
        "Lunes",
        "Martes",
        "Miércoles",
        "Jueves",
        "Viernes",
        "Sábado",
      ],
      dayNamesShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
      dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"],
      monthNames: [
        "Enero",
        "Febrero",
        "Marzo",
        "Abril",
        "Mayo",
        "Junio",
        "Julio",
        "Agosto",
        "Septiembre",
        "Octubre",
        "Noviembre",
        "Diciembre",
      ],
      monthNamesShort: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Ago",
        "Sep",
        "Oct",
        "Nov",
        "Dic",
      ],
      chooseYear: "Elegir año",
      chooseMonth: "Elegir mes",
      chooseDate: "Elegir fecha",
      prevDecade: "Década anterior",
      nextDecade: "Década siguiente",
      prevYear: "Año anterior",
      nextYear: "Año siguiente",
      prevMonth: "Mes anterior",
      nextMonth: "Mes siguiente",
      prevHour: "Hora anterior",
      nextHour: "Hora siguiente",
      prevMinute: "Minuto anterior",
      nextMinute: "Minuto siguiente",
      prevSecond: "Segundo anterior",
      nextSecond: "Segundo siguiente",
      am: "a. m.",
      pm: "p. m.",
      today: "Hoy",
      weekHeader: "Sem",
      firstDayOfWeek: 0,
      showMonthAfterYear: false,
      dateFormat: "dd/mm/yy",
      weak: "Débil",
      medium: "Medio",
      strong: "Fuerte",
      passwordPrompt: "Ingrese una contraseña",
      searchMessage: "{0} resultados disponibles",
      selectionMessage: "{0} elementos seleccionados",
      emptySelectionMessage: "No hay elementos seleccionados",
      emptySearchMessage: "No se encontraron resultados",
      fileChosenMessage: "{0} archivos",
      noFileChosenMessage: "No se eligió ningún archivo",
      emptyMessage: "No hay opciones disponibles",
      aria: {
        trueLabel: "Verdadero",
        falseLabel: "Falso",
        nullLabel: "No seleccionado",
        star: "1 estrella",
        stars: "{star} estrellas",
        selectAll: "Todos los elementos seleccionados",
        unselectAll: "Todos los elementos deseleccionados",
        close: "Cerrar",
        previous: "Anterior",
        next: "Siguiente",
        navigation: "Navegación",
        scrollTop: "Ir al inicio",
        moveTop: "Mover al principio",
        moveUp: "Mover hacia arriba",
        moveDown: "Mover hacia abajo",
        moveBottom: "Mover al final",
        moveToTarget: "Mover al destino",
        moveToSource: "Mover al origen",
        moveAllToTarget: "Mover todo al destino",
        moveAllToSource: "Mover todo al origen",
        pageLabel: "Página {page}",
        firstPageLabel: "Primera página",
        lastPageLabel: "Última página",
        nextPageLabel: "Página siguiente",
        prevPageLabel: "Página anterior",
        rowsPerPageLabel: "Filas por página",
        jumpToPageDropdownLabel: "Ir a página desde lista",
        jumpToPageInputLabel: "Ir a página desde entrada",
        selectRow: "Fila seleccionada",
        unselectRow: "Fila deseleccionada",
        expandRow: "Fila expandida",
        collapseRow: "Fila colapsada",
        showFilterMenu: "Mostrar menú de filtros",
        hideFilterMenu: "Ocultar menú de filtros",
        filterOperator: "Operador del filtro",
        filterConstraint: "Restricción del filtro",
        editRow: "Editar fila",
        saveEdit: "Guardar edición",
        cancelEdit: "Cancelar edición",
        listView: "Vista de lista",
        gridView: "Vista de cuadrícula",
        slide: "Diapositiva",
        slideNumber: "Diapositiva {slideNumber}",
        zoomImage: "Ampliar imagen",
        zoomIn: "Ampliar",
        zoomOut: "Reducir",
        rotateRight: "Girar a la derecha",
        rotateLeft: "Girar a la izquierda",
      },
    },
    unstyled: true,
    pt: {
      datatable: {
        root: "not-prose",
        table: "table table-zebra",
      },
      paginator: {
        root: "py-4",
        content: "flex justify-center items-center gap-4 flex-wrap",
        pages: "flex gap-4",
        first: "btn btn-sm",
        prev: "btn btn-sm",
        next: "btn btn-sm",
        last: "btn btn-sm",
        page: "btn btn-sm data-[p-active=true]:btn-secondary",
      },
      select: {
        root: "input input-bordered flex gap-2 items-center justify-center",
        list: "menu bg-base-100 rounded-btn",
        label: "outline-none",
      },
      contextmenu: {
        root: "menu bg-base-100 shadow rounded-btn",
        itemlink: "flex gap-2",
      },
    },
    theme: {
      /*       preset: Aura, */
      options: {
        darkModeSelector: false,
      },
    },
  });
};
